image: maven:3.6.3

pipelines:
 branches:
  feature/*:
   - step:
      name: Mulesoft Build and Test
      caches:
       - maven
      script:
       - echo "Building the Mulesoft Application`"
       - mvn clean install
  develop:
    - step:
       name: Mulesoft Build and Test
       caches:
        - maven
       script:
        - echo "Building the Mulesoft Application"
        - mvn clean install
    - step:
       name: Mulesoft Deployment to Development Environment
       deployment: Development
       caches:
        - maven
       script:
        - echo "Deploying the Mulesoft Application to Development Environment"
        - mvn deploy -DmuleDeploy -Danypoint.platform.environment=development -Dapplication.name=repository -Dmule.env=dev
        - Dapplication.runtimeVersion=4.3.0 -Dapplication.region=us-east-2 -Dapplication.workers=1 -Dapplication.workerType=MICRO
        - Danypoint_platform_client_id= $client_id_dev
        - Danypoint_platform_client_secret= $client_secret_dev